services:

  dataset-review-website:
    extends:
      file: docker/compose.yaml
      service: dataset-review-website
    depends_on:
      - database
    env_file:
      - config.env
    # volumes:
    #   - /home/frank_regal/storage/datasets/EgoNRG-Full/data/review/videos:/root/dataset_review_website/public/videos

  database:
    image: postgres:15
    container_name: website-db
    environment:
      - POSTGRES_USER=frank-Regal
      - POSTGRES_PASSWORD=inOrbit
      - POSTGRES_DB=website-db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgrest:
    image: postgrest/postgrest
    container_name: website-db-api
    ports:
      - "3001:3000"
    environment:
      PGRST_DB_URI: postgres://frank-Regal:inOrbit@database:5432/website-db
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: frank-Regal
    depends_on:
      - database

volumes:
  postgres_data: