services:
  dataset-review-website:
    # Basic container configuration
    image: fregal/dataset-review-website:latest
    container_name: dataset-review-website
    network_mode: host
    
    # Build configuration
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - HOST_USER=${UNAME}
        - HOST_UID_GID=${UID_GID}
    # Runtime configuration
    entrypoint: /entrypoint.sh -u "$UID_GID" -n "$UNAME"
    stdin_open: true 
    tty: true
    
    # Environment configuration
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - CHOKIDAR_USEPOLLING=true  # Enable hot reloading in Docker
      - WATCHPACK_POLLING=true     # Enable webpack file watching
    
    # Security configuration
    security_opt:
      - apparmor:unconfined
      
    # Volume mounts
    volumes:
      - ../../dataset_review_website:/root/dataset_review_website
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/dri:/dev/dri
      - ${HOME}/.Xauthority:/root/.Xauthority:rw

    working_dir: /root/dataset_review_website
    command: sh -c "npm install"
